### ISSUE TITLE
I'm retarded and too cheap to buy x3t

### ISSUE THREAD

**Issue by ghost** [XtrmJosh/tibia-teamspeak#2]
Idk if you're updating it still but it doesn't respond to any commands, hope to hear back from u! :)

**Comment by TheJoshGriffith** [comment]
Hey, hope you worked it out already, didn't get any notification as you closed the issue already, but basically when the bot is started you have to say !admin to it from one account, and that account will always have permissions to control it. After that, you can add other admins and permissions using the !sg command. It's badly documented but the code itself should be fairly easy to read, and you can see all commands and the "brain" of the application in TeamSpeakReceiver.py.
